### ISSUE TITLE
Detects app as browser

### ISSUE THREAD

**Issue by kishlayk** [fbsamples/messenger-bot-samples#31] opened 2018-03-22 20:49 UTC
Detects messenger app as browser and shows -

> Please Try in Messenger App

![whatsapp image 2018-03-23 at 02 13 09](https://user-images.githubusercontent.com/8452862/37797649-691b1e96-2e40-11e8-9a19-bc6231f99388.jpeg)

**System info**

![whatsapp image 2018-03-23 at 02 16 09](https://user-images.githubusercontent.com/8452862/37797684-83ada1f2-2e40-11e8-93d6-c195612be7c5.jpeg)

**Comment by eunicocornelius** [comment] 2018-06-04 15:16
This also happened for my iPhone 6, Please fix this
![img_4419](https://user-images.githubusercontent.com/33506106/40925860-fceda4b8-681a-11e8-8c2f-5b2cf865bafd.PNG)

**Comment by 756gzdz5** [comment] 2018-06-09 12:15
The fact that the chat extension example hasn't been working for months now, leaves the impression that Facebook is already letting them die.

**Comment by amuramoto** [comment] 2018-06-12 17:40
Additional info available in https://github.com/fbsamples/messenger-bot-samples/issues/30

**Comment by IanLawrence** [comment] 2018-06-12 17:45
Actually there is no further info at all in #30 Maybe a short explanation such as 'For business reasons' or 'Too busy to make it work' etc would make folks happier?

**Comment by eunicocornelius** [comment] 2018-06-13 12:01
Why did you close #30 and this issue? It's still not resolved and you are closing these issues just by referencing it towards each other.

**Comment by embee8** [comment] 2018-07-07 16:36
@eunicocornelius, this issue was never closed. #30 was closed and merged with this one, since it's the same root cause.

I just pushed a maintenance commit which fixed this issue. I tested the extension with the latest Messenger versions on Android and iOS. In fact, the extension now also works on messenger.com.

**Closed by embee8** 2018-07-07 16:36 UTC

**Comment by andrewkmin** [comment] 2018-09-26 08:27
Would like to revisit this. Currently experiencing the same problem.
