### ISSUE TITLE
Messenger app not detected

### ISSUE THREAD

**Issue by operman18** [fbsamples/messenger-bot-samples#41] opened 2019-05-17 07:45 UTC
Hello,

I followed all steps included inside the readme for chat-extensions. But I always get the viewing outside messenger page. I tried on two different phones.
I used those commands
```
heroku create
heroku addons:create heroku-postgresql
heroku config:set WEBHOOK_TOKEN='{MYSECRETTOKEN}'
heroku config:set APP_URL='{MYAPPURL}'
git subtree push --prefix chat-extensions/ heroku master

# I configured the app and the page details before executing those commands
heroku config:set PAGE_ACCESS_TOKEN='{MYAPPTOKEN}'
curl -X POST -H "Content-Type: application/json" -d '{  "whitelisted_domains":["{MYAPPURL}"]}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token={MYAPPTOKEN}"
```

I also whitelisted my app inside page setiings and sucessfully subscribe my webhook to the page. The bot can sends message and even display the regular  heroku website when the app is destroyed.
![Screenshot_2019-05-17-14-26-40-155_com facebook orca](https://user-images.githubusercontent.com/30746044/57911588-5bbaee80-78b2-11e9-8441-13f5549c74f7.png)

**Comment by embee8** [comment] 2019-05-17 15:57
Two things:

- You are running a version of this project that is at least three commits behind HEAD. Please update before proceeding with further debugging.
- You don't have to call the Messenger Profile API manually to whitelist the app URL. This happens automatically on startup (see [here](https://github.com/fbsamples/messenger-bot-samples/blob/master/chat-extensions/app.js#L137)). Remove the `curl` call and check whether your app URL is listed in the whitelisted domains section of your Facebook Page Settings > Messenger Platform.

**Comment by operman18** [comment] 2019-05-18 13:48
Hi, I've checked the setup. I removed the whitelisting:
```
git checkout 09047858e453ba81839c8ee09c8b713d38ede31a
heroku create
heroku addons:create heroku-postgresql
heroku config:set APP_URL='{MYAPPURL}'
heroku config:set WEBHOOK_TOKEN='{MYSECRETTOKEN}'
git subtree push --prefix chat-extensions heroku master

# 1. I created a new app
# 2. I created a new page
# 3. I set up the webhook
# 4. I gave the app permission over the new page
# 5. I subscribed the page to the app's webhook
# 6. I removed generated my PAGE_ACCESS_TOKEN

heroku config:set PAGE_ACCESS_TOKEN='{MYPAGEACCESSTOKEN}'
```

**Comment by embee8** [comment] 2019-06-25 13:39
Closing this issue since the described behavior cannot be reproduced on [the official project page](https://m.me/MessengerTaskBot) which is deployed from this repository. If the issue persists, please also check [this comment](https://github.com/fbsamples/messenger-bot-samples/issues/39#issuecomment-487828278) which describes the circumstances under which this error message can show up. Besides an incorrect domain whitelist, a missing app review would render the same message for users who are not associated with the app through an assigned role.

**Closed by embee8** 2019-06-25 13:39 UTC
