### ISSUE TITLE
Messenger App detected as Web (again)

### ISSUE THREAD

**Issue by andrewkmin** [fbsamples/messenger-bot-samples#35] opened 2018-09-26 08:35 UTC
Would like to revisit this. Currently experiencing the same problem on iOS 12 on iPhone X.

This may be out of scope, but why initialize via Messenger extension? What would be steps to go about decoupling this from the Messenger extension, and thus getting rid of the root issue altogether? Thanks. @embee8

_Originally posted by @andrewkmin in https://github.com/fbsamples/messenger-bot-samples/issues/31#issuecomment-424630500_

**Comment by embee8** [comment] 2018-11-17 03:40
@andrewkmin, I cannot reproduce the issue on http://m.me/MessengerTaskBot. Is that where you are experiencing the problem?
With regards to the latter: The task list is not only initialized by the extension, but is the extension. If by decoupling you mean moving it to the browser, you would lose all context and not be able to tie it back to the conversation.

**Closed by embee8** 2018-11-17 03:40 UTC

**Comment by andrewkmin** [comment] 2018-11-17 11:59
Will check this out

**Comment by eoinclancy1** [comment] 2019-04-20 20:59
Currently experiencing the same issue on iOS 12.2 on iPhone Xs. It keeps telling me to access the service via the native app, which is where I am
